name: flutter_covid
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Functional programming thingies
  dartz: ^0.10.0
  # Value equality
  equatable: ^2.0.3
  # Networking
  dio: ^4.0.0
  # Bloc for state management
  flutter_bloc: ^7.3.0
  # Service locator
  get_it: ^7.2.0
  injectable: ^1.4.1
  # GetX for route, state & dependency management
  get: ^4.3.8
  # Like kotlin sealed class
  freezed_annotation: ^0.14.2
  # Responsive UI util
  flutter_screenutil: ^5.0.0+2
  # Chart widget
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.1.2
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  # Service locator
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
